services:
  frontend:
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./apps/backend
    env_file:
      - ./apps/backend/.env
    environment:
      POSTGRES_HOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:15
    env_file:
      - ./apps/backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

volumes:
  postgres_data: